### ISSUE TITLE
Kairosdb publisher did not notify if is unable to publish data

### ISSUE THREAD

**Issue by PatrykMatyjasek** [intelsdi-x/snap-plugin-publisher-kairosdb#14]
**Snap daemon version** (use `snapteld -v`): snapteld version 1.0.0
**Kairos version**: https://github.com/intelsdi-x/snap-plugin-publisher-kairosdb/releases/tag/2

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- **Kernel** (e.g. `uname -a`): 3.10.0-327.28.3.el7.x86_64
- **Running on docker**

**What happened**:
When running task with running kairosdb publisher, data aren't published in DB. Task worked fine without any fails. Missing data was caused by wrong configuration of cassandra cluster. But i think that user should be notified that publisher wasn't able to publish data.

**What you expected to happen**:
If publisher is not able to put data in proper DB, there user should be notificatied (warning log, task failure, etc.) that something is wrong with configuration.

**Steps to reproduce it** (as minimally and precisely as possible):
1. Run KairosDB for example without cassandra (wrong configuration)
2. Run task which publish data to Kairos
3. Check if it fails

**Comment by kdembler** [comment]
Wasn't able to reproduce the bug.
According to [KairosDB documentation](https://kairosdb.github.io/docs/build/html/restapi/AddDataPoints.html#response) the only way by which we can tell if publishing was successful is checking if the response code was 204 NO CONTENT, which is done by the plugin [here](https://github.com/intelsdi-x/snap-plugin-publisher-kairosdb/blob/master/publisher/publisher.go#L198-L204).

Possible bug with KairosDB itself, closing.
