### ISSUE TITLE
Use dynamic namespace for tagging ?

### ISSUE THREAD

**Issue by julcollas** [intelsdi-x/snap-plugin-publisher-kairosdb#15]
Hi,

Did you thought about using dynamic namespace for tagging metrics like what we can see in the influxdb publsher with the _isMultiFields_ config?

For example with metric **/intel/procfs/cpu/*/user_percentage** from cpu collector and a 2 CPU server, the metric will be

```
- /intel/procfs/cpu/user_percentage plugin_running_on=host1 cpu=0
- /intel/procfs/cpu/user_percentage plugin_running_on=host1 cpu=1
```

instead of

```
- /intel/procfs/cpu/0/user_percentage plugin_running_on=host1
- /intel/procfs/cpu/1/user_percentage plugin_running_on=host1
```

Thanks

Julien

**Comment by mkleina** [comment]
Thank you for your request! You're right, it will make published metrics more consistent. We will add it in the future.

**Comment by julcollas** [comment]
I've made something to start :)
https://github.com/julcollas/snap-plugin-publisher-kairosdb/commit/7b82af4c0c0493ebea1ac15f3bf2471c6a9f4546

**Comment by jcooklin** [comment]
Julien, what is left in your impl for it to be "complete"? Do you intend to
implement and contribute the feature?

**Comment by julcollas** [comment]
I make it configurable in https://github.com/julcollas/snap-plugin-publisher-kairosdb/commit/7b59938ffe6465a8aff5d220aad55b8d3317017a.
It's better like that :)
